#!/bin/sh

DIR="$( cd "$( dirname "$0" )" && pwd )"

# Check to see if we're installed or not
evmtest=$(type -p evmtest) # Find in path
if [ -e "${evmtest}" ]; then
	_evmdir=$(dirname "${evmtest}")
	prefix=${_evmdir%%/bin}
	EVMDIR=${prefix}/share/evmtest
else
	EVMDIR=$DIR
fi

. "$EVMDIR"/files/common.sh
usage (){
	echo "Usage:"
	echo "	evmtest runtest <test name> [OPTIONS]"
	echo
	echo "Options:"
	echo "	-h	Displays this help message"
	echo "	-v	Verbose logging"
	echo "List of tests: [R] = Must be run as root"
	echo

	# Any test should be added here manually
	# The reason this is manual is to prevent the accidental / malicious
	# placement of a script in tests/
	echo "[R]	boot_aggregate"
	echo "[R]	env_validate"
	echo "[ ]	examples_test"
	echo "[R]	kexec_sig"
	echo "[R]	kmod_sig"
	echo "[R]	policy_sig"
	echo "[R]	xattr_preserve"

	echo ""
	echo "Note: Tests may be run directly from the \"tests\" directory"
}


runtest (){
	local test_name=$1
	shift

	if [ ! -e "$EVMDIR"/tests/"$test_name".sh ]; then
		echo "[!] Test: \"$test_name\" not found"
		usage
		exit 1
	else
		("$EVMDIR"/tests/"$test_name".sh "$@")
	fi
}

if [ $# -eq 0 ]; then
	usage
	exit 1
elif [ "$1" = "-h" ]; then
	usage
	exit 0
elif [ "$1" = "runtest" ]; then
	if [ -z "$2" ]; then
		echo "[!] Provide a test"
		exit
	else
		shift
		runtest "$@"
		exit $?
	fi
else
	usage
fi
