#!/bin/sh

DIR="$( cd "$( dirname "$0" )" && pwd )"

# Check to see if we're installed or not
evmtest=$(type -p evmtest) # Find in path
if [ -e "${evmtest}" ]; then
	_evmdir=$(dirname "${evmtest}")
	prefix=${_evmdir%%/bin}
	EVMDIR=${prefix}/share/evmtest
else
	EVMDIR=$DIR
fi

. "$EVMDIR"/files/common.sh
usage (){
	echo "Usage:"
	echo "	evmtest runtest <test name> [OPTIONS]"
	echo "	evmtest	runall <configuration file>"
	echo
	echo "Options:"
	echo "	-h	Displays this help message"
	echo "	-v	Verbose logging"
	echo "List of tests: [R] = Must be run as root"
	echo

	# Any test should be added here manually
	# The reason this is manual is to prevent the accidental / malicious
	# placement of a script in tests/
	echo "[R]	boot_aggregate"
	echo "[R]	env_validate"
	echo "[ ]	examples_test"
	echo "[R]	kexec_sig"
	echo "[R]	kmod_sig"
	echo "[R]	policy_sig"
	echo "[R]	xattr_preserve"

	echo ""
	echo "Note: Tests may be run directly from the \"tests\" directory"
}


runtest (){
	local test_name=$1
	shift

	if [ ! -e "$EVMDIR"/tests/"$test_name".sh ]; then
		echo "[!] Test: \"$test_name\" not found"
		usage
		exit 1
	else
		("$EVMDIR"/tests/"$test_name".sh "$@")
	fi
}

if [ $# -eq 0 ]; then
	usage
	exit 1
elif [ "$1" = "-h" ]; then
	usage
	exit 0
elif [ "$1" = "runtest" ]; then
	if [ -z "$2" ]; then
		echo "[!] Provide a test"
		exit
	else
		shift
		runtest "$@"
		exit $?
	fi
elif [ "$1" == "runall" ]; then
	if [ -z "$2" ] || [ ! -e "$2" ]; then
		echo "evmtest runall <config file>"
		echo "[!] Please provide a config file"
		exit 1
	fi
	source "$2" # Load in config
	if [ "$VERBOSE" -eq 1 ]; then
		V="-v"
	fi

	# Key is not optional
	if [ -z "$IMA_KEY" ]; then
		echo "[*] Please correct your config file"
		exit 1
	fi

	EVMTEST_require_root
	FAIL=0
	echo "[*] Running tests..."
	# 1
	"$EVMDIR"/tests/env_validate.sh -r "$V"
	FAIL=$((FAIL+$?))
	# 2
	if [ -z "$KERN_IMAGE" ]; then
		"$EVMDIR"/tests/kexec_sig.sh -k "$IMA_KEY" "$V"
	else
		"$EVMDIR"/tests/kexec_sig.sh -k "$IMA_KEY" -i \
			"$KERN_IMAGE" "$V"
	fi
	FAIL=$((FAIL+$?))
	# 3
	if [ -z "$KBUILD_DIR" ]; then
		"$EVMDIR"/tests/kmod_sig.sh -k "$IMA_KEY" "$V"
	else
		"$EVMDIR"/tests/kmod_sig.sh -b "$KBUILD_DIR" \
			-k "$IMA_KEY" "$V"
	fi
	FAIL=$((FAIL+$?))
	# 4
	"$EVMDIR"/tests/policy_sig.sh -k "$IMA_KEY" "$V"
	FAIL=$((FAIL+$?))
	# 5
	"$EVMDIR"/tests/boot_aggregate.sh "$V"
	FAIL=$((FAIL+$?))
	# 6
	"$EVMDIR"/tests/xattr_preserve.sh "$V"
	FAIL=$((FAIL+$?))
	echo "..."
	echo "[*] TESTS PASSED: $((6-FAIL))"
	echo "[*] TESTS FAILED: $FAIL"
else
	usage
fi
